DROP TABLE IF EXISTS public.target;

CREATE TABLE target (
    target_id int8 generated by default as identity,
    circle_id int8 not null,
    kpi_id int8 not null,
    target_value numeric not null,
    created_at timestamp default current_timestamp not null,
    updated_at timestamp,
    PRIMARY KEY (target_id),
    CONSTRAINT fk_kpi FOREIGN KEY(kpi_id) REFERENCES kpi_definition(kpi_id),
    CONSTRAINT fk_circle FOREIGN KEY(circle_id) REFERENCES circle(circle_id),
    CONSTRAINT unique_circle_kpi unique (circle_id, kpi_id)
);