name: "Migrate database schema"

on:
  push:
    branches:
      - main
    paths:
      - "src/migrations/**"

jobs:
  migrate-database:
    name: Run Flyway migrations
    runs-on: ubuntu-20.04
    env:
      SUPABASE_PORT: 5432
      SUPABASE_USER: postgres
      SUPABASE_DB: postgres
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    steps:
      - uses: actions/checkout@v2
      - run: >-
          docker run --rm
          --volume ${{ github.workspace }}/src/migrations:/flyway/sql:ro
          flyway/flyway:latest
          -url="jdbc:postgresql://${{ secrets.SUPABASE_DB_HOST }}:${{ env.SUPABASE_PORT }}/${{ env.SUPABASE_DB }}?sslmode=require"
          -user="${{ env.SUPABASE_USER }}"
          -password="${{ secrets.SUPABASE_PASS }}"
          migrate
